#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - pgbackrest
  - postgresql-16
  - wget

write_files:
  - path: /usr/local/bin/setup-pgbackrest-test-stanza.sh
    content: |
      #!/bin/bash
      set -euo pipefail

      # Setup pgbackrest source database for testing
      echo "Setting up pgbackrest source database..."

      # Initialize source PostgreSQL cluster
      sudo -u postgres /usr/lib/postgresql/16/bin/initdb -D /var/lib/postgresql/16/test-source -k -A peer

      # Create pgbackrest repository and set permissions
      mkdir -p /var/lib/pgbackrest
      sudo chmod 750 /var/lib/pgbackrest
      sudo chown postgres:postgres /var/lib/pgbackrest

      # Create pgbackrest configuration
      sudo tee /etc/pgbackrest.conf > /dev/null << 'EOF'
      [test-stanza]
      pg1-path=/var/lib/postgresql/16/test-source
      pg1-port=5433

      [global]
      repo1-path=/var/lib/pgbackrest
      process-max=2
      EOF

      # Configure source database for archiving
      sudo tee -a /var/lib/postgresql/16/test-source/postgresql.conf > /dev/null << 'EOF'
      archive_command = 'pgbackrest --stanza=test-stanza archive-push %p'
      archive_mode = on
      wal_level = replica
      port = 5433
      EOF

      # Start source database
      sudo -u postgres /usr/lib/postgresql/16/bin/pg_ctl start -D /var/lib/postgresql/16/test-source -l /var/log/postgresql/test-source.log

      # Wait for database to be ready
      sudo -u postgres /usr/lib/postgresql/16/bin/pg_isready -p 5433

      # Create test database and sample data
      sudo -u postgres /usr/lib/postgresql/16/bin/psql -p 5433 -c "CREATE DATABASE testdb;"
      sudo -u postgres /usr/lib/postgresql/16/bin/psql -p 5433 -d testdb -c "
        CREATE TABLE users (name VARCHAR(100) NOT NULL);
        INSERT INTO users (name) VALUES ('Alice'), ('Bob'), ('Charlie');
      "

      # Create pgbackrest stanza and initial backup
      sudo -u postgres pgbackrest --stanza=test-stanza stanza-create

      # Force checkpoint to speed up backup
      sudo -u postgres /usr/lib/postgresql/16/bin/psql -p 5433 -c "CHECKPOINT;"

      # Run backup with timeout
      timeout 120 sudo -u postgres pgbackrest --stanza=test-stanza backup || echo "Backup completed or timed out"

      echo "pgbackrest setup complete"

runcmd:
  # Create ZFS disk files for testing
  - truncate -s 5G /zfs-disk1
  - truncate -s 5G /zfs-disk2

  # Install Go 1.24
  - wget https://go.dev/dl/go1.24.0.linux-arm64.tar.gz -O /tmp/go1.24.0.linux-arm64.tar.gz
  - tar -C /usr/local -xzf /tmp/go1.24.0.linux-arm64.tar.gz
  - ln -sf /usr/local/go/bin/go /usr/local/bin/go
  - rm /tmp/go1.24.0.linux-arm64.tar.gz

  # Setup pgbackrest test stanza
  - chmod 755 /usr/local/bin/setup-pgbackrest-test-stanza.sh
  - /usr/local/bin/setup-pgbackrest-test-stanza.sh

final_message: "Done!"
