name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate protobuf files
        run: |
          protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/quic.proto

      - name: Build releases
        run: |
          # Build quic
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/quickr-dev/quic/internal/version.Version=${{ steps.version.outputs.version }}'" -o quic-darwin-amd64 ./cmd/quic
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'github.com/quickr-dev/quic/internal/version.Version=${{ steps.version.outputs.version }}'" -o quic-darwin-arm64 ./cmd/quic
          GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/quickr-dev/quic/internal/version.Version=${{ steps.version.outputs.version }}'" -o quic-linux-amd64 ./cmd/quic
          GOOS=linux GOARCH=arm64 go build -ldflags="-X 'github.com/quickr-dev/quic/internal/version.Version=${{ steps.version.outputs.version }}'" -o quic-linux-arm64 ./cmd/quic

          # Build quicd
          GOOS=darwin GOARCH=amd64 go build -o quicd-darwin-amd64 ./cmd/quicd
          GOOS=darwin GOARCH=arm64 go build -o quicd-darwin-arm64 ./cmd/quicd
          GOOS=linux GOARCH=amd64 go build -o quicd-linux-amd64 ./cmd/quicd
          GOOS=linux GOARCH=arm64 go build -o quicd-linux-arm64 ./cmd/quicd

      - name: Generate checksums
        run: |
          shasum -a 256 quic* > checksums.txt
          cat checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            quic-darwin-amd64
            quic-darwin-arm64
            quic-linux-amd64
            quic-linux-arm64
            quicd-darwin-amd64
            quicd-darwin-arm64
            quicd-linux-amd64
            quicd-linux-arm64
            checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
